### PR TITLE
Add macro support (for CaseClassDom)

### PR DESCRIPTION
**Pull request by insperatum**

### CODE REVIEW

**Comment by fayimora** [comment]
:+1:

**Comment by riedelcastro** [comment]
Thanks guys! Btw, is it possible for g8 to use the current wolfe snapshot if the generated project is a snapshot?

**Comment by insperatum** [comment]
I don't understand... What do you mean 'if the generated project is a snapshot'?

**Comment by riedelcastro** [comment]
One could make the "version" parameter of the build file a g8 parameter, and if it's a SNAPSHOT version it should use a snapshot wolfe dependency. (I am a bit concerned to depend on 0.5.0 because we already added quite a few fixes)

**Comment by fayimora** [comment]
I agree. I think all versions(sbt, scala and wolfe) should be parameters(with the latest as default). 

With regards to checking if the wolfe version is a snapshot, do you mean checking if the [latest release](https://github.com/wolfe-pack/wolfe/releases) is a snapshot?

**Comment by riedelcastro** [comment]
Sounds good. I hadn't even thought of making the wolfe version parametrized, but this makes sense. As for checking for snapshots: if the user specifies a snapshot version for their project, the default wolfe version would also be the latest SNAPSHOT version. Otherwise it would be the latest release version.

**Comment by fayimora** [comment]
Great. I'll send a PR later today :smiley:

**Pull request merged**
